spin_manifest_version = 2

[application]
name = "mstd-wsj-rss"
version = "0.0.1"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = "mstd.seungjin.net/@wsj"

[variables]
internal_key = { required = true }
wsj_rss_uri = { required = true }
wsj_mstd_api_uri = { required = true }
wsj_mstd_access_token = { required = true }

[[trigger.cron]]
component = "wsj-rss"
cron_expression = "*/10 * * * * *"

[component.wsj-rss]
source = "target/wasm32-wasip1/release/wsj_rss.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = ["https://www..wsjcom", "https://mstd.seungjin.net"]

[component.wsj-rss.variables]
rss_uri = "{{ wsj_rss_uri }}"
mstd_api_uri = "{{ wsj_mstd_api_uri }}"
mstd_access_token = "{{ wsj_mstd_access_token }}"

[component.wsj-rss.build]
command = "cargo build --target wasm32-wasip1 --release"
